background #28272A
foreground #F2F3EB

selection_background #F2F3EB
selection_foreground #28272A

cursor #F2F3EB

color0 #535356
color1 #3A7BCF
color2 #769191
color3 #559F52
color4 #D78AC0
color5 #4FCAFE
color6 #DADDC5
color7 #E4E6DA

color8 #A0A198
color9 #3A7BCF
color10 #769191
color11 #559F52
color12 #D78AC0
color13 #4FCAFE
color14 #DADDC5
color15 #E4E6DA