include colors.conf

font_family      DepartureMono Nerd Font
font_size 12.0

disable_ligatures never

enable_audio_bell no

shell zsh

url_style curly

remember_window_size no

background_opacity 0.80

scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

confirm_os_window_close 0

sync_to_monitor no

clear_all_shortcuts no

map ctrl+shift+a launch --type=background --stdin-source=@screen sh -c "cat | wl-copy"